apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-realm-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  genai-toolkit-realm.json: {{ .Files.Get "files/genai-toolkit-realm.json" | b64enc }}