apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-toolkit-nginx
  labels:
    app: genai-toolkit-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-toolkit-nginx
  template:
    metadata:
      labels:
        app: genai-toolkit-nginx
    spec:
      containers:
        - name: genai-toolkit-nginx
          {{- if not .Values.devTag }}
          image: {{ .Values.dockerRegistry }}nginx:{{ .Chart.Version }}
          {{- else }}
          image: {{ .Values.dockerRegistry }}nginx:{{ .Values.devTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: genai-toolkit-nginx
spec:
  type: LoadBalancer
  selector:
    app: genai-toolkit-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: api