{{- if (and (eq .Values.db.connectionString "") (not .Values.localTesting)) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgvector
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgvector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}