apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-toolkit-rag-api
  labels:
    app: genai-toolkit-rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-toolkit-rag-api
  template:
    metadata:
      labels:
        app: genai-toolkit-rag-api
    spec:
      initContainers:
        - name: wait-for-api
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://genai-toolkit-api.{{ .Release.Namespace }}.svc.cluster.local:8001/health; do echo waiting for genai-toolkit-api; sleep 2; done']
      containers:
        - name: genai-toolkit-rag-api
          {{- if not .Values.localTesting }}
          image: {{ .Values.dockerRegistry }}genai-toolkit-rag-api:{{ .Chart.Version }}
          {{- else }}
          image: localhost:5005/genai-toolkit-rag-api:{{ .Values.devTag }}
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
              protocol: TCP
              name: http
            - containerPort: 8003
              protocol: TCP
              name: sockets
          env:
            - name: ROOT_DIR
              value: {{ .Values.volumesMountPoint }}
            - name: JWT_SECRET_KEY
              value: "whatever"
            - name: DB_CONNECTION_STRING
              value: {{ if .Values.db.connectionString }}
                        {{ .Values.db.connectionString | quote }}
                      {{ else }}
                        {{ printf "Host=postgres.%s.svc.cluster.local;Port=5432;Database=genai-toolkit-db;Username=admin;Password=admin" .Release.Namespace }}
                      {{ end }}
          volumeMounts:
            - name: rsa-keys-volume
              mountPath: /keys/public
            {{- if ne .Values.cloudProvider "local" }}
              {{- range $index, $nfs_volumes := (splitList "," .Values.nfs.volumes) }}
                {{- $nfs_volume_parts := splitList ":" $nfs_volumes }}
                {{- $concatString :=  printf "%s/%s%s" $.Values.volumesMountPoint $.Values.cloudProvider (index $nfs_volume_parts 1)}}
            - name: nfs-volume-{{ $index }}
              mountPath: {{ $concatString }}
              {{- end }}
            {{- else }}
            - name: nfs-volume-0
              mountPath: {{ .Values.volumesMountPoint }}/ontap/{{ (splitList "/" .Values.localDir | last) }}
            {{- end }}
      volumes:
        - name: rsa-keys-volume
          secret:
            secretName: rsa-keys
            items:
              - key: public_key.rsa
                path: public_key.rsa
        {{- if ne .Values.cloudProvider "local" }}
          {{- range $index, $nfs_volumes := (splitList "," .Values.nfs.volumes) }}
            {{- $nfs_volume_parts := splitList ":" $nfs_volumes }}
        - name: nfs-volume-{{ $index }}
          persistentVolumeClaim:
            claimName: netapp-nfs-pvc-{{ $index }}
          {{- end }}
        {{- else }}
        - name: nfs-volume-0
          hostPath:
            path: {{ .Values.localDir }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: genai-toolkit-rag-api
  labels:
    app: genai-toolkit-rag-api
spec:
  selector:
    app: genai-toolkit-rag-api
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: http
    - protocol: TCP
      port: 8003
      targetPort: 8003
      name: sockets