apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "patch", "update", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
subjects:
- kind: ServiceAccount
  name: secret-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
---
{{- if or (eq .Values.apiv2.secretStore "iam") (eq .Values.apiv2.secretStore "kubernetes") }}
{{- if eq .Values.apiv2.secretStore "iam" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceaccount-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-serviceaccounts
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.apiv2.serviceAccount.name | default "genai-toolkit-api-sa" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: serviceaccount-reader
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- if eq .Values.apiv2.secretStore "kubernetes" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: genai-toolkit-api-secrets-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "patch", "update", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genai-toolkit-api-read-write-secrets
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.apiv2.serviceAccount.name | default "genai-toolkit-api-sa" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: genai-toolkit-api-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiv2.serviceAccount.name | default "genai-toolkit-api-sa" }}
  {{- with .Values.apiv2.serviceAccount.labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.apiv2.serviceAccount.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}