apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-toolkit-ui
  labels:
    app: genai-toolkit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-toolkit-ui
  template:
    metadata:
      labels:
        app: genai-toolkit-ui
    spec:
      containers:
        - name: genai-toolkit-ui
          image: {{ .Values.dockerRegistry }}genai-toolkit-ui:{{ .Chart.Version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: "AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://azurite-lb.default.svc.cluster.local:10000/devstoreaccount1;QueueEndpoint=http://azurite-lb.default.svc.cluster.local:10001/devstoreaccount1;TableEndpoint=http://azurite-lb.default.svc.cluster.local:10002/devstoreaccount1;"
            - name: AZURE_STORAGE_QUEUE_NAME
              value: "debug-log"
---
apiVersion: v1
kind: Service
metadata:
  name: genai-toolkit-ui
  labels:
    app: genai-toolkit-ui
spec:
  selector:
    app: genai-toolkit-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000