apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-constring
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  POSTGRES_CONNECTION_STRING: |
    {{- if not .Values.db.connectionString }}
      {{ printf "Host=postgres.%s.svc.cluster.local;Port=5432;Database=genai-toolkit-db;Username=admin;Password=admin" .Release.Namespace  }}
    {{- else }}
      {{ .Values.db.connectionString | quote }}
    {{- end }}