name: genai-toolkit
services:
    postgres:
        image: pgvector/pgvector:pg16
        container_name: postgres
        networks:
            - genai-toolkit-network
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-genai-toolkit-db}
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: POSTGRES_PASSWORD_PLACEHOLDER
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-genai-toolkit-db} -U ${POSTGRES_USER:-admin}"]
            interval: 2s
            timeout: 5s
            retries: 60
        volumes:
            - /databases/postgres:/var/lib/postgresql/data
        command: ["postgres", "-c", "idle_session_timeout=360000", "-c", "log_statement=all", "-c", "log_line_prefix=%m | %a | '%i' | SessionCommandCount: %c | "]

    genai-toolkit-auth:
        stop_signal: SIGINT
        image: us-docker.pkg.dev/gcnv-ai-dev/genai-toolkit/genai-toolkit-auth:v0.4
        networks:
            - genai-toolkit-network
        container_name: genai-toolkit-auth
        healthcheck:
                test: ["CMD-SHELL", "curl -v http://localhost:4659/health || exit 1"]
                interval: 5s
                timeout: 2s
                retries: 10
        environment:
            DB_NAME: ${POSTGRES_DB:-genai-toolkit-db}
            DB_USER: ${POSTGRES_USER:-admin}
            DB_PASSWORD: POSTGRES_PASSWORD_PLACEHOLDER
            DB_HOST: postgres
            DB_PORT: 5432
            PORT: 4659
            PRIVATE_KEY_FILE: rs256.rsa
            AUTH_TABLE_NAME: auth_svc_authentication
            USER_TABLE_NAME: auth_svc_users
            TOKEN_TABLE_NAME: auth_svc_token
            LOG_LEVEL: WARNING
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - /root/.auth-keys:/root_dir

    genai-toolkit-api:
        stop_signal: SIGINT
        image: us-docker.pkg.dev/gcnv-ai-dev/genai-toolkit/genai-toolkit-api:v0.4
        container_name: genai-toolkit-api
        networks:
            - genai-toolkit-network
        healthcheck:
            test: ["CMD-SHELL", "curl -v http://localhost:8001/health || exit 1"]
            interval: 5s
            timeout: 2s
            retries: 10
        environment:
            ROOT_DIR: /root_dir
            RAGAS_HOST: http://genai-toolkit-ragas:8002
            ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=genai-toolkit-db;Username=admin;Password=POSTGRES_PASSWORD_PLACEHOLDER
        depends_on:
            postgres:
                condition: service_healthy
            genai-toolkit-auth:
                condition: service_healthy
        volumes:
            - /volumes:/root_dir
            - /root/.auth-keys/:/keys

    genai-toolkit-ragas:
        stop_signal: SIGINT
        image: us-docker.pkg.dev/gcnv-ai-dev/genai-toolkit/genai-toolkit-ragas:v0.4
        container_name: genai-toolkit-ragas
        networks:
            - genai-toolkit-network
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8002/health/']
            interval: 5s
            timeout: 2s
            retries: 10
        environment:
            ROOT_DIR: /root_dir
            POSTGRES_HOST: postgres
            POSTGRES_PASSWORD: POSTGRES_PASSWORD_PLACEHOLDER
            JWT_AUTH_REQUIRED: True
            JWT_SECRET_KEY: JWT_SECRET_KEY_PLACEHOLDER
            PYTHONUNBUFFERED: 1
            FORCE_COLOR: True
        volumes:
            - /volumes/:/root_dir
            - /cache/api:/app/.cache
            - /root/.auth-keys/:/keys
        depends_on:
            postgres:
                condition: service_healthy
            genai-toolkit-api:
                condition: service_healthy

    genai-toolkit-ui:
        image: us-docker.pkg.dev/gcnv-ai-dev/genai-toolkit/genai-toolkit-ui:v0.4
        container_name: genai-toolkit-ui
        networks:
            - genai-toolkit-network
        depends_on:
            genai-toolkit-api:
                condition: service_healthy
            genai-toolkit-ragas:
                condition: service_healthy

    nginx:
        image: us-docker.pkg.dev/gcnv-ai-dev/genai-toolkit/nginx:v0.4
        container_name: nginx
        networks:
            - genai-toolkit-network
        ports:
            - "80:80"
            - "443:443"
            - "8001:8001"
            - "8002:8002"
            - "4659:4659"
        depends_on:
            - genai-toolkit-api
            - genai-toolkit-ui
            - genai-toolkit-ragas

networks:
    genai-toolkit-network:
        driver: bridge
